### ISSUE TITLE
declare optional schema on streamsync state

### ISSUE THREAD

**Issue by FabienArcellier** [FabienArcellier/streamsync#24]
This proposal aims to provide a way to associate a streamsync state with an explicit schema. The developer can specify how the state he builds in streamsync is structured.

This parameter is optional. If it is not provided, the current behavior which consists of interpreting dictionaries as substates is preserved.

This mechanism may solve 3 problems:

* specifies the type and allows plotly or vegas payloads not to be interpreted as a state (https://github.com/streamsync-cloud/streamsync/issues/226)
* provides a way to specify calculated states (https://github.com/streamsync-cloud/streamsync/discussions/182)
* offer autocompletion in a handler

The developer would have access to autocompletion in the handler from his IDE.

Here is a first draft of what this mechanism could produce.

```python
from typing import Optional

import streamsync as ss
from streamsync.core import State, StreamsyncState

class AppState(State):
    title: str
    stats: State

class RootState(StreamsyncState):
    myapp: AppState
    _my_private_element: int
    message: Optional[str]
    counter: int
    graph: dict
    stats: streamsync.State

    @streamsync.property(depends_on=['graph'])
    def graph_size(self):
        return len(self.graph["data"])

# Its name starts with _, so this function won't be exposed
def _update_message(state: RootState):
    state.myapp.title = "My App"
    state['myapp']['title'] = "My App"
    
    state.set_page('hello')

initial_state = ss.init_state({
    "my_app": {
        "title": "My App"
    },
    "graph": {
        "data": [
            {
                "x": [
                    "giraffes",
                    "orangutans",
                    "monkeys"
                ],
                "y": [
                    20,
                    14,
                    23
                ],
                "type": "bar"
            }
        ]
    },
    "_my_private_element": 1337,
    "message": None,
    "counter": 26,
    "stats": {
        "increment": 0,
        "decrement": 0
    }
}, schema=RootState)

_update_message(initial_state)

initial_state.import_stylesheet('main', '/static/main.css')
```

**Comment by raaymax** [comment]
I really like the idea, looks good to me.
Simple and straightforward, and easy to understand by reading the code.
